"""Added other models

Revision ID: 634a22b2c3e3
Revises: e58c9449f0e9
Create Date: 2025-02-25 17:49:49.081776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '634a22b2c3e3'
down_revision = 'e58c9449f0e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('genreId', sa.Integer(), nullable=False),
    sa.Column('isbn', sa.Integer(), nullable=False),
    sa.Column('pages', sa.Integer(), nullable=False),
    sa.Column('chapters', sa.Integer(), nullable=False),
    sa.Column('coverPicture', sa.String(length=500), nullable=False),
    sa.Column('yearPublished', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['genreId'], ['genres.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookshelves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('friends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('friendId', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'rejected', name='friend_status'), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['friendId'], ['users.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookclubs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ownerId', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('bookId', sa.Integer(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bookId'], ['books.id'], ),
    sa.ForeignKeyConstraint(['ownerId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookshelf_books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bookshelfId', sa.Integer(), nullable=False),
    sa.Column('bookId', sa.Integer(), nullable=False),
    sa.Column('addedAt', sa.DateTime(), nullable=False),
    sa.Column('orderInShelf', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bookId'], ['books.id'], ),
    sa.ForeignKeyConstraint(['bookshelfId'], ['bookshelves.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bookId', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('review', sa.String(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bookId'], ['books.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookclub_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bookclubId', sa.Integer(), nullable=False),
    sa.Column('bookId', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('chapter', sa.Integer(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bookId'], ['books.id'], ),
    sa.ForeignKeyConstraint(['bookclubId'], ['bookclubs.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookclub_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bookclubId', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('joinedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bookclubId'], ['bookclubs.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('firstName',
               existing_type=sa.VARCHAR(length=225),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('lastName',
               existing_type=sa.VARCHAR(length=225),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('lastName',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=225),
               existing_nullable=False)
        batch_op.alter_column('firstName',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=225),
               existing_nullable=False)

    op.drop_table('bookclub_members')
    op.drop_table('bookclub_comments')
    op.drop_table('reviews')
    op.drop_table('bookshelf_books')
    op.drop_table('bookclubs')
    op.drop_table('friends')
    op.drop_table('bookshelves')
    op.drop_table('books')
    op.drop_table('genres')
    # ### end Alembic commands ###
