"""Make isbn column unique

Revision ID: 7bfb2a00df7e
Revises: d83e6f49e026
Create Date: 2025-02-24 20:51:14.815548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bfb2a00df7e'
down_revision = 'd83e6f49e026'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_books_isbn', ['isbn'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
         batch_op.drop_constraint('uq_books_isbn', type_='unique')

    # ### end Alembic commands ###
